version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S"
    format: '[%(asctime)s.%(msecs)03dZ] %(name)s %(levelprefix)s %(message)s'
  access:
    "()": uvicorn.logging.AccessFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S"
    format: '[%(asctime)s.%(msecs)03dZ] %(name)s %(levelprefix)s %(message)s'
  colorized:
    "()": uvicorn.logging.ColourizedFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S"
    format: '[%(asctime)s.%(msecs)03dZ] %(name)s %(levelprefix)s %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
  console:
    formatter: colorized
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: DEBUG
    handlers: [ default ]
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers: [ access ]
    propagate: no
  dap.app:
    level: INFO
    handlers: [ console ]
    propagate: no
  dap.app.debug:
    level: DEBUG
    handlers: [ console ]
    propagate: no
root:
  level: INFO
  handlers: [ console ]
