version: '3.0'

services:
  dap-api:
    container_name: dap-api
    image: disaster-area-portal
    restart: "unless-stopped"
    depends_on:
      dap-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./dap_api/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./dap_api/app:/app
    env_file:
      - .env
    entrypoint: [
        "/start.sh"
    ]
  dap-db:
    container_name: dap-db
    image: dap-storage
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: ./dap_db/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./dap_db/pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
