"""Add custom_speeds table

Revision ID: 1accb4baabfc
Revises: 2fa00d59041d
Create Date: 2021-05-03 14:55:35.022186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1accb4baabfc'
down_revision = '2fa00d59041d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_speeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_speeds_created'), 'custom_speeds', ['created'], unique=False)
    op.create_index(op.f('ix_custom_speeds_description'), 'custom_speeds', ['description'], unique=False)
    op.create_index(op.f('ix_custom_speeds_id'), 'custom_speeds', ['id'], unique=False)
    op.create_index(op.f('ix_custom_speeds_name'), 'custom_speeds', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_speeds_name'), table_name='custom_speeds')
    op.drop_index(op.f('ix_custom_speeds_id'), table_name='custom_speeds')
    op.drop_index(op.f('ix_custom_speeds_description'), table_name='custom_speeds')
    op.drop_index(op.f('ix_custom_speeds_created'), table_name='custom_speeds')
    op.drop_table('custom_speeds')
    # ### end Alembic commands ###
