"""create: Move default & create index

Revision ID: 2fa00d59041d
Revises: 9683b9c7b361
Create Date: 2020-12-15 21:43:25.587576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa00d59041d'
down_revision = '9683b9c7b361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_disaster_areas_created'), 'disaster_areas', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disaster_areas_created'), table_name='disaster_areas')
    # ### end Alembic commands ###
