"""Init

Revision ID: 2ff9aa36b88c
Revises:
Create Date: 2020-12-03 16:01:40.398273

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2ff9aa36b88c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('hashed_secret', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('providers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_providers_description'), 'providers', ['description'], unique=False)
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=True)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('disaster_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_disaster_types_description'), 'disaster_types', ['description'], unique=False)
    op.create_index(op.f('ix_disaster_types_id'), 'disaster_types', ['id'], unique=False)
    op.create_index(op.f('ix_disaster_types_name'), 'disaster_types', ['name'], unique=True)
    op.create_table('disaster_sub_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['disaster_types.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_disaster_sub_types_description'), 'disaster_sub_types', ['description'], unique=False)
    op.create_index(op.f('ix_disaster_sub_types_id'), 'disaster_sub_types', ['id'], unique=False)
    op.create_index(op.f('ix_disaster_sub_types_name'), 'disaster_sub_types', ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_email'), table_name='providers')
    op.drop_index(op.f('ix_providers_description'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_disaster_sub_types_name'), table_name='disaster_sub_types')
    op.drop_index(op.f('ix_disaster_sub_types_id'), table_name='disaster_sub_types')
    op.drop_index(op.f('ix_disaster_sub_types_description'), table_name='disaster_sub_types')
    op.drop_table('disaster_sub_types')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_disaster_types_name'), table_name='disaster_types')
    op.drop_index(op.f('ix_disaster_types_id'), table_name='disaster_types')
    op.drop_index(op.f('ix_disaster_types_description'), table_name='disaster_types')
    op.drop_table('disaster_types')
    # ### end Alembic commands ###
