"""Add disaster areas

Revision ID: 38f87d7065af
Revises: 2ff9aa36b88c
Create Date: 2020-12-05 15:33:24.218825

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '38f87d7065af'
down_revision = '2ff9aa36b88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_areas',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('provider_id', sa.Integer(), nullable=False),
                    sa.Column('d_type_id', sa.Integer(), nullable=False),
                    sa.Column('ds_type_id', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT',
                                                                 name='geometry'), nullable=True),
                    sa.ForeignKeyConstraint(['d_type_id'], ['disaster_types.id'], ),
                    sa.ForeignKeyConstraint(['ds_type_id'], ['disaster_sub_types.id'], ),
                    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_disaster_areas_description'), 'disaster_areas', ['description'], unique=False)
    op.create_index(op.f('ix_disaster_areas_id'), 'disaster_areas', ['id'], unique=False)
    op.create_index(op.f('ix_disaster_areas_name'), 'disaster_areas', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disaster_areas_name'), table_name='disaster_areas')
    op.drop_index(op.f('ix_disaster_areas_id'), table_name='disaster_areas')
    op.drop_index(op.f('ix_disaster_areas_description'), table_name='disaster_areas')
    op.drop_table('disaster_areas')
    # ### end Alembic commands ###
