"""Convert d_area geom column to MultiPolygon

Revision ID: 9e9c67334499
Revises: 1accb4baabfc
Create Date: 2021-08-11 12:24:14.779011

"""
import geoalchemy2
from alembic import op

# revision identifiers, used by Alembic.
revision = '9e9c67334499'
down_revision = '1accb4baabfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disaster_areas', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True, postgresql_using='st_multi(geom)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.alter_column('disaster_areas', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True, postgresql_using='st_geometryn(geom, 1)')
    # ### end Alembic commands ###
