"""Update tables

Revision ID: d810a2163028
Revises: 38f87d7065af
Create Date: 2020-12-08 19:01:34.515635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd810a2163028'
down_revision = '38f87d7065af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_disaster_areas_geom', table_name='disaster_areas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_disaster_areas_geom', 'disaster_areas', ['geom'], unique=False)
    # ### end Alembic commands ###
